# Generated by Django 4.0 on 2022-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_profile_status_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
