# Generated by Django 4.0 on 2022-01-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_profile_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='signature',
            field=models.TextField(null=True),
        ),
    ]
